## Numpy array and basic

In [9]:
import numpy as np

print(np.__version__)




2.4.6


### Creating array from list

## test


ctr + enter for the same cell and shit + enter  for different cell

press (a)  for add cell in above 

press (b) for add cell at below

for mode change you have to first in escape mode the press (m or y) for markedown and code respectively

for delete press (dd) to delete current cell

# List vs Array

In [ ]:
py_list = [1,2,3]
print("python list multiplication ", py_list*2)

np_array = np.array([1,2,3])  # element wise multiplication 
print("python array multiplication ",np_array*2)

python list multiplication  [1, 2, 3, 1, 2, 3]
python array multiplication  [2 4 6]


## creating array from scratch

In [ ]:
zeros = np.zeros((3,4))
print("zeros array :\n",zeros)
print("\n")

ones = np.ones((3,4))
print("ones array :\n",ones)
print("\n")

full = np.full((3,3),7)
print("full array :\n",full)
print("\n")

random = np.random.random((2,3))
print("random array :\n",random)
print("\n")

sequence = np.arange(0,10,2)
print("sequence array", sequence)


zeros array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ones array :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


full array :
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


random array :
 [[0.81069993 0.26825622 0.51726902]
 [0.03382132 0.78513186 0.58954526]]


sequence array [0 2 4 6 8]


### Vector,Matix and Tensor

In [ ]:
vector = np.array([1,2,3])
print("vector : ",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix : ",matrix)

tensor =np.array([[[1,2],[3,4],[5,6],[7,8]]])

print("tensor : ",tensor)

vector :  [1 2 3]
matrix :  [[1 2 3]
 [4 5 6]]
tensor :  [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


### Array property:--

In [ ]:
arr =np.array([[1,2,3],[4,5,6]])

print("shape:",arr.shape)
print("Dimension:",arr.ndim)

print("size:",arr.size)
print("Dtype :",arr.dtype)



shape: (2, 3)
Dimension: 2
size: 6
Dtype : int64


### Array Reshaping


In [11]:



arr =np.arange(12)
print("original array ", arr)
print("\n")

reshaped =arr.reshape((3,4))
print("reshaped array ", reshaped)

print("\n")


flattened =reshaped.flatten()
print("flattened array ", flattened)

## ravel (return original array , instead of copy)
raveled = reshaped.ravel()
print("raveled array ",raveled)
print("\n")



transpose =reshaped.T
print("transposed array ",transpose)


original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]


reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]


transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
