## Numpy Array operations

In [2]:
import numpy as np

In [3]:
arr =np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing", arr[2:7])
print("with step",arr[1:8:2])
print("negative indexing",arr[-3])

basic slicing [3 4 5 6 7]
with step [2 4 6 8]
negative indexing 8


In [6]:
arr_2d = np.array([[1,2,3],[4,5,6],[6,7,8]])

print("specific element",arr_2d[1,2])

print("entire row",arr_2d[1])
print("entire coloum",arr_2d[:,1])


specific element 6
entire row [4 5 6]
entire coloum [2 5 7]


## sorting

In [11]:
unsorted = np.array([3,2,5,6,78,1,39,4])
print("sorted array",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array by coloum",np.sort(arr_2d_unsorted ,axis=0))
print("sorted 2d array by row",np.sort(arr_2d_unsorted ,axis=1))

sorted array [ 1  2  3  4  5  6 39 78]
sorted 2d array by coloum [[1 1]
 [2 2]
 [3 3]]
sorted 2d array by row [[1 3]
 [1 2]
 [2 3]]


## filter


In [13]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = number[number%2==0]
print("enven number ",even_number)

enven number  [ 2  4  6  8 10]


## Filter with mask

In [15]:
mask = number>5
print("Numbers greater than 5",number[mask])

Numbers greater than 5 [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [17]:
indices = [0,2,4]
print(number[indices])

where_result =np.where(number>5)
print(where_result)
print("NP where", number[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [20]:
condition_array = np.where(number>5,number*2,number)
print("condition aray",condition_array)

condition_array = np.where(number>5,"true","false")
print("condition aray",condition_array)


condition aray [ 1  2  3  4  5 12 14 16 18 20]
condition aray ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and removing the data

In [23]:
arr1 =np.array([1,2,3])
arr2 =np.array([4,5,6])

combined = arr1+ arr2
print(combined)

concat = np.concatenate((arr1,arr2))
print(concat)


[5 7 9]
[1 2 3 4 5 6]


### array compatibility

In [29]:
a =np.array([1,2,3])
b =np.array([12,22,32])
c =np.array([13,23,33,222])

print("compatibility shape:" ,a.shape==b.shape)
print("compatibility shape:" ,a.shape==c.shape)




compatibility shape: True
compatibility shape: False


In [37]:
original =np.array([[1,2],[3,4]])
new_row =np.array([[5,6]])

with_new_row =np.vstack((original,new_row))
print(original)
print("\n")
print(with_new_row)

new_col =np.array([[7],[8]])
with_new_col =np.hstack((original,new_col))
print("\n")

print("with new coloum ", with_new_col)

[[1 2]
 [3 4]]


[[1 2]
 [3 4]
 [5 6]]


with new coloum  [[1 2 7]
 [3 4 8]]


In [39]:
arr =np.array([1,2,3,4,5,6])
deleted =np.delete(arr,2)
print("Array after deletion :",deleted)

Array after deletion : [1 2 4 5 6]
